name: Otto Test

on: [push]

jobs:
  test:
    name: Test with Otto
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.18
    - name: Get Otto
      run: |
        go install github.com/robertkrimen/otto/otto@latest
    - name: Test
      run: |
        # otto otto_tests/test.js
        otto lib/luxon.js